@token=glpat-2ReyRiZF4YDuC6F2wASm

### - List groups - ###
GET https://gitlab.dillards.com/api/v4/groups/ HTTP/1.1
PRIVATE-TOKEN: {{token}}


### - List runners - ###
GET https://gitlab.dillards.com/api/v4/runners/ HTTP/1.1
PRIVATE-TOKEN: {{token}}


### - Get Projects ###
GET https://gitlab.dillards.com/api/v4/projects/ HTTP/1.1
PRIVATE-TOKEN: {{token}}


### - Get Project ###
GET https://gitlab.dillards.com/api/v4/projects/1580 HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Get Pipeline ###
GET https://gitlab.dillards.com/api/v4/projects/7/pipelines/?status=manual HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Get Jobs ###
GET https://gitlab.dillards.com/api/v4/projects/700/jobs?scope[]=manual HTTP/1.1
PRIVATE-TOKEN: {{token}}

###

GET https://gitlab.dillards.com/api/v4/users?state=active HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Play a job
GET https://gitlab.dillards.com/api/v4/projects/7/jobs/557/play HTTP/1.1
PRIVATE-TOKEN: {{token}}

status == "manual"
job.stage == .step
job.ref = ref
