@token=pJChuA1JhqKTD4NyFko1
### - Find all projects - ####
GET https://gitlab.dillards.com/api/v4/projects?per_page=5 HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - List jobs - ###
GET https://gitlab.dillards.com/api/v4/projects/7/jobs HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Get Project ###
GET https://gitlab.dillards.com/api/v4/projects/7 HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Get Pipeline ###
GET https://gitlab.dillards.com/api/v4/projects/7/pipelines/?status=manual HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Get Jobs ###
GET https://gitlab.dillards.com/api/v4/projects/700/jobs?scope[]=manual HTTP/1.1
PRIVATE-TOKEN: {{token}}

### - Play a job
GET https://gitlab.dillards.com/api/v4/projects/7/jobs/557/play HTTP/1.1
PRIVATE-TOKEN: {{token}}

status == "manual"
job.stage == .step
job.ref = ref
